### ISSUE TITLE
Fatal signal 11 on domoticz beta caused by use of positional parameter in plugin.py

### ISSUE THREAD

**Issue by rwaaren** [ffes/domoticz-buienradar#10]
triggered by the description on Github (https://github.com/domoticz/domoticz/issues/2092), I changed line 177 in plugin.py of the buienradar plugin.
CODE: SELECT ALL

<comment> # old line with positional parameters  this line will trigger a fatal signal 11 on my system
Devices[Unit].Update(nValue, str(sValue))     

<Comment> # New line with named parameters
Devices[Unit].Update(nValue=nValue, sValue=str(sValue))
With this change my local compiled domoticz keeps running.

**Comment by SargonofAssyria** [comment]
I can confirm that it is working correctly with that change.
