### ISSUE TITLE
Domoticz Python changes - first in Bèta 3.7602 - Buienradar stopped working 

### ISSUE THREAD

**Issue by Sneeuwtijger** [ffes/domoticz-buienradar#7]
Hi, 
Major changes in the Python part of Domoticz - 
See http://www.domoticz.com/forum/viewtopic.php?f=65&t=17554&p=135840
and https://github.com/domoticz/domoticz/pull/1571

All info coming from this thread https://www.domoticz.com/forum/viewtopic.php?f=6&t=17778

**Comment by ffes** [comment]
Strange, because the changes that are mention in advance warning are not used by my plugin.

I will test ASAP and see if I can fix it.

**Comment by Sneeuwtijger** [comment]
Oké, take care ;)

**Comment by jeroenonline** [comment]
This might not be plugin-related, as [this user](https://gathering.tweakers.net/forum/view_message/51728409) stated it could have something to do with a default CMake option that seems to have changed. For me this fixed it, so try changing "USE_PYTHON:BOOL=OFF" to "ON" in file CMakeCache.txt and recompile domoticz again.
