### ISSUE TITLE
Buienradar device does not show under devices

### ISSUE THREAD

**Issue by Willow69** [ffes/domoticz-buienradar#9]
Hi, i am new with domoticz and i tried to follow your instructions to the letter but de buienradar device does not show up under domotcz devices. What am i doin wrong? 
Setup, Hardware in your Domoticz interface does not show Buienradar. The  python3 localtest.py command works.
I'm using this version of Domoticz:

About Domoticz
Version: 3.8590
Build Hash: d63b4c1

pi@RASDOMOTICZ:~/domoticz/plugins/domoticz-buienradar $ python3 localtest.py    XML file contains weather station information
Found Meetstation Lauwersoog (ID: 6277) at 7.7 km from your home location
No Barometer and Visibility info found in your weather station, getting info from weather station De Bilt
Temperature: 13.2
Wind Speed: 3.36 | Wind Bearing: 209.0 | Wind Direction: SSW | Wind Speed Gusts: 5.1 | Wind Chill: 13.2
Barometer: 1011.32 | Barometer Forecast: 3
Humidity: 97 | Humidity status: 3
Visibility: 21500.0
Solar Irradiance: None
Rain rate: 0.1
Weather prediction today: Herfstachtig (Opgesteld op vrijdag 20 okt 2017 om 11:15)

**Comment by tommie44** [comment]
Hi, I know it's almost a year later, but even so I hope this will be usefull to someone.
I experienced the same problem (now on domoticz V4.97)
My solution was found under Setup/Settings/Other:
EventSystem (Lua/Blockly/Scripts) needs to be enabled or activated for the python plugins to work.
Don't forget to restart the domoticz service after changing, and good luck!
